# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d724aff417c313fc2f5c052f555af3fadd86f10f1dbb44c4421153f5cee93e7d3150b59cc478ea8131732d5d6c66df703c3a9e8069e7109941347c53ba2409db

test:
  secret_key_base: 50d03b0f82fa6379adee75ade74cc7bf1f6deaceec6f48513f8c46b7917a6151a5a60f837e0e27f392bcf4348f7302c2a981e1c2ad762a99e9550cb8731fdab3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
